language: erlang
otp_release:
- R16B
- 19.3.6
- 18.3.4
- 17.4.0
before_script:
- kerl list installations
- kerl status
- kerl list builds
- kerl list releases || true
- kerl update releases
- curl -#fSLo ./rebar3 https://s3.amazonaws.com/rebar3/rebar3 && chmod +x ./rebar3
- export PATH="$PATH:$PWD"
- rebar3 version
script:
- DEBUG=1 rebar3 eunit
- |
  git clone https://github.com/fenollp/otp_vsn_testing.git
  cd otp_vsn_testing
  rebar3 do eunit,release
  ! [ -f include/internal_otp_vsn.hrl ]
