language: erlang
matrix:
  fast_finish: true
  include: # More reliable mapping than what docker/erlang:* provides
  - otp_release: 20.3
    env: _OTP_VSN=20.3.2 _OTP_VSN_M=20 _OTP_VSN_m=3 _OTP_VSN_P=2
  - otp_release: 20.0
    env: _OTP_VSN=20.0.5 _OTP_VSN_M=20 _OTP_VSN_m=0 _OTP_VSN_P=5
  - otp_release: 19.3
    env: _OTP_VSN=19.3 _OTP_VSN_M=19 _OTP_VSN_m=3 _OTP_VSN_P=6
  - otp_release: 18.3.4
    env: _OTP_VSN=18.3.4 _OTP_VSN_M=18 _OTP_VSN_m=3 _OTP_VSN_P=4
  - otp_release: 18.2.1
    env: _OTP_VSN=18.2.1 _OTP_VSN_M=18 _OTP_VSN_m=2 _OTP_VSN_P=1
  - otp_release: 17.5
    env: _OTP_VSN=17.5.0 _OTP_VSN_M=17 _OTP_VSN_m=5 _OTP_VSN_P=0
  - otp_release: R16B03-1
    env: _OTP_VSN=16.3.1 _OTP_VSN_M=16 _OTP_VSN_m=3 _OTP_VSN_P=1
  - otp_release: R16B
    env: _OTP_VSN=16.0.0 _OTP_VSN_M=16 _OTP_VSN_m=0 _OTP_VSN_P=0
before_script:
- |
  git clone --branch 3.5.0 https://github.com/erlang/rebar3.git
  cd rebar3 && ./bootstrap
  mv -v rebar3 ~/.local/bin
  export PATH="$PATH:$HOME/.local/bin"
- rebar3 version
script:
- DEBUG=1 rebar3 eunit
- |
  git clone https://github.com/fenollp/otp_vsn_testing.git
  cd otp_vsn_testing
  rebar3 do eunit,release
  ! [ -f include/internal_otp_vsn.hrl ]
