version: 2
workflows:
  version: 2
  tests:
    jobs:
    - test_20.3
    - test_20.0
    - test_19.3.6.2
    - test_19.3
    - test_18.3
    - test_17.5

eunit: &eunit
- checkout
- run: rebar3 eunit

jobs:

  test_20.3:
    docker:
      - image: erlang:20.3
    steps: *eunit

  test_20.0:
    docker:
      - image: erlang:20.0
    steps: *eunit

  test_http://19.3.6.2:
    docker:
      - image: erlang:19.3.6.2
    steps: *eunit

  test_19.3:
    docker:
      - image: erlang:19.3
    steps: *eunit

  test_18.3:
    docker:
      - image: erlang:18.3
    steps: *eunit

  test_17.5:
    docker:
      - image: erlang:17.5
    steps: *eunit
