version: 2
workflows:
  version: 2
  gen_workflow:
    jobs: ['gen']
  nightly:
    jobs: ['gen']
    triggers:
      - schedule:
          cron: '0 0 * * *'  #= @daily
          filters:
            branches:
              only: ['master']

jobs:

  gen:
    docker: [image: 'python:3-alpine']
    steps:
    - run: apk update && apk upgrade && apk add make curl git
    - checkout
    - run: make gen
