version: 2
workflows:
  version: 2
  tests:
    jobs:
    - test_20.3.2
    - test_20.0.5
    - test_19.3.6.2
    - test_19.3
    - test_18.3
    - test_17.5

jobs:

  test_20.3.2:
    docker: [image: 'erlang:20.3.2']
    steps: &test_steps
    - checkout
    - run: rebar3 eunit
    - run: git clone https://github.com/fenollp/otp_vsn_testing.git
    - run: cd otp_vsn_testing
    - run: rebar3 do eunit,release

  test_20.0.5:
    docker: [image: 'erlang:20.0.5']
    steps: *test_steps

  test_19.3.6.2:
    docker: [image: 'erlang:19.3.6.2']
    steps: *test_steps

  test_19.3:
    docker: [image: 'erlang:19.3']
    steps: *test_steps

  test_18.3:
    docker: [image: 'erlang:18.3']
    steps: *test_steps

  test_17.5:
    docker: [image: 'erlang:17.5']
    steps: *test_steps
