name: Publish to hex.pm
on: {push: {tags: ['*']}}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        mkdir -p ~/.hex
        echo "$HEX_STUFF" >~/.hex/hex.config

        mkdir -p ~/.config/rebar3
        echo '{plugins, [rebar3_hex]}.' >~/.config/rebar3/rebar.config

        wget -nc https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

        ./rebar3 hex repo auth ci-otp_vsn-2 --key "$HEX_KEY"
        ./rebar3 hex publish <<<y
