name: Tag syncs
on:
  push: {branches: [master]}
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v4
      if: contains(github.event.head_commit.message, 'make gen')
      with:
        github_token: ${{ secrets.TAGGING_TOKEN }} # Triggers a workflow
        default_bump: minor
        tag_prefix: ''
